version: '3.7'
services:
  mongodb:
    image: mongo:6.0.11
    container_name: mongodb_boot
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /Users/heeju/workspace2/practices_1/mongodb/data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root